### ISSUE TITLE
Feature Request: Automatically add new episodes to queue

### ISSUE THREAD

**Issue by sawyersteven** [cardo-podcast/cardo#11]
On a per-subscription basis, provide an option to automatically add all new episodes to the queue.

**Comment by cardo-podcast** [comment]
Fine, I had already planned to add an automatic download feature, implement auto-queue should be easy once auto-download is implemented.
Thanks for the suggestion!

**Comment by cardo-podcast** [comment]
This should work now on https://github.com/cardo-podcast/cardo/releases/tag/1.9.0
