### ISSUE TITLE
No aarch64 DMG for 1.8.0?

### ISSUE THREAD

**Issue by SABRE1982** [cardo-podcast/cardo#13]
There doesn't appear be an Arm version for macOS for the latest release?

**Comment by cardo-podcast** [comment]
Pretty weird, build and assets upload is managed by a github action that didn't reported anything extrange. I re-run this job, the logs seems to be ok [logs here](https://github.com/cardo-podcast/cardo/actions/runs/11307099539/job/31470508566).

I will open an issue on tauri-action, meanwhile you can use x64 version, I think you wont have any problem.

**Comment by cardo-podcast** [comment]
I found the assets on another draft release, I already uploaded it to latest. Will close this issue, thanks.
