### ISSUE TITLE
If it built on web technologies - please make it as a web app - started locally from terminal OR as a browser extension

### ISSUE THREAD

**Issue by vitaly-zdanevich** [cardo-podcast/cardo#15]

**Comment by cardo-podcast** [comment]
Hi, this is feasible but it would be a totally different product.

Currently the app is based on Tauri, that means it's built in a similar way to server-frontend applications, I don't know if Tauri allows to share the frontend in any port to use the app as a server, but I don't think this is a good idea.

The app is intentionally as it is, I reseached a lot before deciding to use Tauri, even when I come from a python/django/flask development stack.

The roadmap is more to be a well-integrated app with the operating system, the bundles are so lightweight that is's not a pain have it installed even on smaller disks or older computers. Sichronization should cope all the server based apps capabilities.

If the FR comes from the mobile usage, I recommend you using Antennapod on Android, I don't know if it exists something like that on iOS, Tauri V2 makes it possible in theory to translate the app to mobile devices, but I don't see that as necessary right now.

However, this is an open source product, you or everyone else are free of forking and make a server based app or wathever, if you need help with that you can ask me. Cheers.
