### ISSUE TITLE
Nextcloud gpoddersync is not syncing

### ISSUE THREAD

**Issue by FiLeonard** [cardo-podcast/cardo#4]
Hi, I came across Cardo when looking for a Windows-compatible podcast app that supports nextcloud-gpoddersync. It was listed as the nextcloud-gpoddersync compatible client on the nextcloud repod gitea page. I got my nextcloud connected, however it doesn't sync with the following error message
![image](https://github.com/user-attachments/assets/189709be-2b01-4ed2-878e-3673b6f0f766)

1.5.1 didn't fix it.

**Comment by cardo-podcast** [comment]
Hi, I gess that the first time you sync Cardo add your old subscriptions to subscription list.
Some podcast details are parsed from feed, I think you have a subscription with a different formed xml, so the app is not ready yet.
You can see the feeds (with the concrete feed url) you are subscribed on `<YOUR NEXTCLOUD URL>/index.php/apps/gpoddersync/subscriptions` In the "add" list.

If it's not a problem for you, you can send me the list, or, to know what podcast it's causing trouble you can add subscriptions manually with the "Add subscription by RSS address" button.

In adition to solve this specific problem I think I could catch the error and let other subscriptions to be added.

Thanks for the report!

**Comment by FiLeonard** [comment]
Hey @cardo-podcast, found the problem. I accidentally added at one point a regular rss-feed to my subscritpion list. But this is generally supported by all the clients i use, e.g. antennapod and repod. So there has been no problem, until now ^^ Maybe it is a potential "feature" to support regular non-podcast rss feeds. But it would be definitly helpful, if you could implement an except for those subscriptions which don't work so the import is not generally aborted. Maybe with some information that the import didn't work for feed xyz.

**Comment by cardo-podcast** [comment]
@FiLeonard good idea! Maybe in next release.
