### ISSUE TITLE
Weird behavior with particular rss feed

### ISSUE THREAD

**Issue by FiLeonard** [cardo-podcast/cardo#7]
The following rss feed is not loaded by the app : https://www.ndr.de/nachrichten/info/podcast4696.xml
If I click on this podcast in the list of subscribed podcasts, it shows basically an ordered list of new episodes across all subscribed podcasts (i think like the home screen). If I click on reload it shows an error message and an empty list of episodes - as expected, because it couldn't load the rss feed: 
![image](https://github.com/user-attachments/assets/feaf1032-c5ee-4847-8d1f-9229bcf1b6ea)

**Comment by cardo-podcast** [comment]
Bug found, thanks for reporting! Unsubscribe and subscribe again and it should work now.

**Comment by FiLeonard** [comment]
tested in 1.6.1. works!
